### ISSUE TITLE
Multiple Select does not work when adding images to a bundle.

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/storybook-packager-public#26] opened 2019-06-13 18:45 UTC
I can not select multiple images at the same time in the Open/Save dialog when adding new images to a bundle.

**Comment by Lin87** [comment] 2019-06-13 19:32
Not a bug. It is working as intended but I'll enhance it to allow multiple selections and update the frame table accordingly.

**Comment by Lin87** [comment] 2019-06-19 17:03
The add frame ➕button can now select multiple images. To be released in build 24.

**Closed by Lin87** 2019-06-19 17:03 UTC
Labels: enhancement
